#!/usr/bin/env bash
set -euo pipefail

# Bump the release version across every file that carries it.
#
# This script is the single authority on which files carry a version (see the
# "Single source of truth" rule in .claude/CLAUDE.md). .claude/commands/git-release.md
# defers to it rather than restating the list. Adding a version to a new file
# means adding it to VERSION_FILES here in the same commit — the stray-declaration
# guard below fails the release otherwise.
#
# Usage: ./scripts/bump-version.sh 2026.3.0

# Files this script rewrites. THE list — not "the list as of when someone last
# updated the docs".
VERSION_FILES=(
    "src-tauri/Cargo.toml"
    "src-tauri/tauri.conf.json"
    "package.json"
)

# Files allowed to contain a version-shaped line for the outgoing version
# without being rewritten: the changelog records every past version by design,
# and lockfiles restate the package version but are regenerated by their own
# tooling, not by this script.
ALLOWED_STALE=(
    "CHANGELOG.md"
    "src-tauri/Cargo.lock"
    "pnpm-lock.yaml"
    # This script's own tests. Their versions are FIXTURES written into temp
    # dirs — a starting point for "rejects a lower version", "accepts a new
    # month" and so on — not a declaration of what the app ships. They collide
    # with the outgoing version only because the fixture happens to equal it,
    # and rewriting them would corrupt the cases they encode.
    "scripts/test-bump-version.sh"
)

die() {
    echo "Error: $*" >&2
    exit 1
}

if [ $# -eq 0 ]; then
    echo "Usage: $0 <version>"
    echo "Example: $0 2026.3.0"
    exit 1
fi

NEW_VERSION="$1"

# Validate version format (CalVer: YYYY.M.P)
if ! [[ $NEW_VERSION =~ ^[0-9]{4}\.[0-9]+\.[0-9]+$ ]]; then
    die "Version must be in CalVer format (YYYY.M.P), e.g., 2026.3.0"
fi

# Return 0 if $1 is strictly greater than $2 under CalVer numeric comparison.
# 10# forces base 10 so a zero-padded component is not read as octal.
version_gt() {
    local -a a b
    IFS=. read -r -a a <<<"$1"
    IFS=. read -r -a b <<<"$2"
    local i
    for i in 0 1 2; do
        if ((10#${a[i]} > 10#${b[i]})); then return 0; fi
        if ((10#${a[i]} < 10#${b[i]})); then return 1; fi
    done
    return 1 # equal is not strictly greater
}

# ---------------------------------------------------------------------------
# Guard 1: the version must move forwards.
#
# Checked against two references, because they catch different regressions:
#
#   - the last tag, which is what consumers resolve; and
#   - the current in-tree version, which is what a source build (Nix) reports.
#
# The June 2026 incident was purely in-tree: the version was bumped across four
# untagged commits to 2026.6.10 and then reset to 2026.6.2. Tags were untouched,
# so a tag-only check would have accepted that reset. Both are needed.
# ---------------------------------------------------------------------------
CURRENT_VERSION=$(sed -n 's/^[[:space:]]*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' \
    src-tauri/tauri.conf.json | head -1)
[ -n "$CURRENT_VERSION" ] || die "Could not read the current version from src-tauri/tauri.conf.json"

if ! version_gt "$NEW_VERSION" "$CURRENT_VERSION"; then
    die "$NEW_VERSION is not greater than the current in-tree version $CURRENT_VERSION.
       Versions must move forwards: a source build of an earlier commit would
       otherwise outrank this one."
fi

LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || true)
if [ -n "$LAST_TAG" ]; then
    LAST_TAG_VERSION="${LAST_TAG#v}"
    if ! version_gt "$NEW_VERSION" "$LAST_TAG_VERSION"; then
        die "$NEW_VERSION is not greater than the last tag $LAST_TAG.
       Releasing it would break auto-updates for users already on $LAST_TAG_VERSION."
    fi
else
    echo "No tags found — skipping the tag monotonicity check (first release)."
fi

# ---------------------------------------------------------------------------
# Guard 2: no file outside VERSION_FILES may declare the outgoing version.
#
# Matches a *declaration* — `version = "X"` or `"version": "X"` — rather than a
# bare occurrence of the version string. Prose legitimately discusses old
# versions (CHANGELOG entries, the comment in flake.nix explaining this very
# bug); a bare-string grep flags all of
# those and trains everyone to ignore it. A declaration is the thing that
# actually rots.
#
# Only tracked files are searched, so build output and node_modules are excluded
# for free.
# ---------------------------------------------------------------------------
version_re="${CURRENT_VERSION//./\\.}"
declaration_re="\"?version\"?[[:space:]]*[:=][[:space:]]*\"?${version_re}\"?"

skip_list=("${VERSION_FILES[@]}" "${ALLOWED_STALE[@]}")
stray=()
while IFS= read -r -d '' file; do
    skip=false
    for allowed in "${skip_list[@]}"; do
        if [ "$file" = "$allowed" ]; then
            skip=true
            break
        fi
    done
    $skip && continue
    # -I skips binary files; a match means this file declares the outgoing version.
    if grep -qIE "$declaration_re" "$file" 2>/dev/null; then
        stray+=("$file")
    fi
done < <(git ls-files -z)

if [ ${#stray[@]} -gt 0 ]; then
    echo "Error: these files declare the outgoing version $CURRENT_VERSION but are not" >&2
    echo "rewritten by this script, so they would rot at this release:" >&2
    printf '  %s\n' "${stray[@]}" >&2
    echo >&2
    echo "Fix by either deriving the version from src-tauri/tauri.conf.json (preferred)" >&2
    echo "or adding the file to VERSION_FILES in $0 — in this same commit." >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# Rewrite. Guards run first so a failure never leaves a half-bumped tree.
# ---------------------------------------------------------------------------
echo "Bumping version $CURRENT_VERSION -> $NEW_VERSION..."

echo "Updating src-tauri/Cargo.toml..."
sed -i.bak "s/^version = \".*\"/version = \"$NEW_VERSION\"/" src-tauri/Cargo.toml
rm src-tauri/Cargo.toml.bak

echo "Updating src-tauri/tauri.conf.json..."
sed -i.bak "s/\"version\": \".*\"/\"version\": \"$NEW_VERSION\"/" src-tauri/tauri.conf.json
rm src-tauri/tauri.conf.json.bak

echo "Updating package.json..."
sed -i.bak "s/\"version\": \".*\"/\"version\": \"$NEW_VERSION\"/" package.json
rm package.json.bak

echo "✓ Version bumped to $NEW_VERSION in ${#VERSION_FILES[@]} files"
echo ""
echo "Next steps:"
echo "  1. Review changes: git diff"
echo "  2. Commit: git add -u && git commit -m \"chore(release): bump version to $NEW_VERSION\""
echo "  3. Tag: git tag v$NEW_VERSION"
echo "  4. Push: git push && git push --tags"
echo "  5. CI will build and create draft release"
echo "  6. Review draft, edit release notes, and publish"
